[package]
name = "language_lalrpop"
version = "0.1.0"
authors = ["Alec Thilenius <alec@thilenius.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.16.3"

[dependencies]
clap = "2.32.0"
lalrpop-util = "0.16.3"
regex = "1.1.0"
