[package]
name = "language_lalrpop"
version = "0.1.0"
authors = ["Alec Thilenius <alec@thilenius.com>"]
edition = "2018"

[dependencies]
cached = "0.8.0"
clap = "2.32.0"
colored = "1.7.0"
lazy_static = "1.2.0"
regex = "1.1.0"
