[package]
name = "language_lalrpop"
version = "0.1.0"
authors = ["Alec Thilenius <alec@thilenius.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
colored = "1.7.0"
lazy_static = "1.2.0"
md5 = "0.6.1"
regex = "1.1.0"
